import React, { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import { gsap, TimelineLite, Power3 } from 'gsap';
import { useEffect, useRef } from 'react';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { decl } from 'postcss';

function Work({ posts }) {
  const allCategories = [
    'AllPoject',
    ...new Set(posts.map((post) => post.category)),
  ];
  const [menuItems, setMenuItems] = useState(posts);
  const [categories, setCategories] = useState(allCategories);

  const filterItems = (category) => {
    if (category === 'AllPoject') {
      setMenuItems(posts);
      return;
    }
    const newItems = posts.filter((post) => post.category === category);
    setMenuItems(newItems);
  };

  return (
    <>
      <Head>
        <title>ripon - work</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>
      <div className='lg:container mx-auto lg:px-6 p-5  md:px-16 z-50'>
        <div className='mt-20'>
          <div className='text-gray-50 sm:flex flex-wrap'>
            <div className='sm:w-1/5 w-full mb-7 '>
              <div className='sm:ml-10'>
                <div className='text-2xl md:text-4xl  ml-2  mb-8 relative font-comorant font-semibold  text-gray-600 capitalize'>
                  <p className='inline-block px-2  relative'>
                    <span className='after__ele relative z-50'>
                      All Projects
                    </span>
                    <span className='absolute opacity-80 bg-purple-200	w-full h-2 md:h-2 left-0 bottom-0 md:bottom-0 z-0'></span>
                  </p>
                </div>
                <ul className='flex sm:flex-col  w-full  overflow-x-auto'>
                  {categories.map((category, index) => {
                    return (
                      <li
                        className='cursor-pointer sm:mb-5 mb-2 mr-2 '
                        type='button'
                        key={index}
                        onClick={() => filterItems(category)}
                      >
                        <a className='sm:text-md px-4 py-1 rounded-lg items-center text-lg font-averia bg-gray-300 text-gray-800 '>
                          #{category}
                        </a>
                      </li>
                    );
                  })}
                </ul>
              </div>
            </div>
            <div className='sm:w-4/5 w-full '>
              <div className='sm:ml-10'>
                <div className='sm:flex justify-center w-full flex-wrap '>
                  {/* card start*/}
                  {menuItems.map((post) => {
                    const { id, title, img, desc, url, view, category, uses } =
                      post;
                    return (
                      <Link href='/' key={id}>
                        <div className=' w-96 sm:mr-8 sm:mb-10 mb-8 sm:mx-px pr-4 mx-auto cursor-pointer overflow-hidden'>
                          <img
                            className='allimages overflow-hidden sm:w-full  h-56	mx-auto rounded '
                            src={img}
                            alt=''
                          />

                          <div className='mt-2'>
                            <span className='text-2xl bloc font-averia capitalize text-gray-800'>
                              {title}
                            </span>
                            <div className='text-sm flex mt-2 cursor-pointer'>
                              <span className='mr-2 rounded px-2 py-1 delay-100 ease-out bg-purple-800 text-gray-200 hover:text-purple-600 hover:bg-gray-200'>
                                {uses.fremwork}
                              </span>
                              <span className='mr-2 rounded px-2 py-1  delay-100 ease-out bg-purple-800 text-gray-200 hover:text-purple-600 hover:bg-gray-200'>
                                {uses.fremwork2}
                              </span>
                              <span className='mr-2 rounded px-2 py-1 delay-100 ease-out	bg-purple-800 text-gray-200 hover:text-purple-600 hover:bg-gray-200'>
                                {uses.fremwork3}
                              </span>
                            </div>
                          </div>
                        </div>
                      </Link>
                    );
                  })}
                  {/* card start*/}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Work;

export async function getServerSideProps() {
  const res = await fetch('https://riponhaldar.github.io/json-api/db.json');
  const post = await res.json();

  return {
    props: {
      posts: post,
    },
  };
}
