import React, { useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import { gsap, TimelineLite, Power3 } from 'gsap';
import { useEffect, useRef } from 'react';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
import link from 'next/link';
function Work({ posts }) {
  // Animation
  let card = useRef(null);
  let tl = new TimelineLite({ delay: 0.2 });

  useEffect(() => {
    const allCards = gsap.utils.toArray('.uls .lis');

    tl.from('ul li', {
      duration: 0.4,
      x: -10,
      opacity: 0,
      stagger: 0.4,
    }).from(
      '.uls',
      {
        duration: 1.8,
        x: -10,
        opacity: 0,
        stagger: 0.4,
      },
      '-=0.8'
    );
    allCards.forEach((card) => {
      tl.from(
        card,

        {
          duration: 5,
          opacity: 0,
          y: 120,
          scrollTrigger: {
            scrub: true,
            trigger: card,
            start: 'top bottom-=100',
            end: 'bottom bottom-=100',
            // markers: true,
          },
        }
      );
    });
    // tl.from('.uls .lis', {
    //   duration: 5,
    //   opacity: 0,
    //   x: -50,
    //   scrollTrigger: {
    //     scrub: true,
    //     trigger: '.lis',
    //     start: 'top bottom-=100',
    //     end: 'bottom bottom-=200',
    //     markers: true,
    //   },
    // });
  });
  // all project categories
  const allCategories = ['All', ...new Set(posts.map((post) => post.category))];
  const [menuItems, setMenuItems] = useState(posts);
  const [categories, setCategories] = useState(allCategories);

  const filterItems = (category) => {
    if (category === 'All') {
      setMenuItems(posts);
      return;
    }
    const newItems = posts.filter((post) => post.category === category);
    setMenuItems(newItems);
  };
  const img = {
    width: '100%',
  };

  return (
    <>
      <Head>
        <title>ripon - work</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>
      <div className='lg:container mx-auto lg:px-6 p-5  md:px-16 z-50'>
        <div className='mt-20'>
          <ul className='catagray w-full flex justify-center text-center align-middle text-gray-50'>
            {categories.map((category, index) => {
              return (
                <li
                  className='mr-2 px-2 rounded text-red-50 hover:bg-gray-100 hover:text-gray-900'
                  type='button'
                  key={index}
                  onClick={() => filterItems(category)}
                >
                  {category}
                </li>
              );
            })}
          </ul>
          <div className='mt-4 allcards'>
            <div className='uls flex flex-wrap'>
              {/* car worksparts*/}
              {menuItems.map((post) => {
                const { id, title, img, desc, url, view, category } = post;
                return (
                  <div
                    key={id}
                    className='lis relative md:flex md:mt-40 items-center	e mt-10 justify-between'
                    ref={(el) => (card = el)}
                  >
                    <div className='xl:mr-20 mr-10 mb-10'>
                      <p className='text-red-100 text-2xl capitalize  font-serif mb-4'>
                        {title}
                      </p>
                      <span className='text-red-100 text-base'>{desc}</span>
                      <div className='text-gray-100 mt-4'>{category}</div>
                      <div className='flex mt-4'>
                        <div className='mr-2'>
                          <Link href={view}>
                            <a className='bg-gray-50 py-1 px-2 font-bold text-red-800 rounded'>
                              Live
                            </a>
                          </Link>
                        </div>
                        <div>
                          <Link href={url}>
                            <a className='bg-gray-50 py-1 px-2 font-bold text-red-800 rounded'>
                              sources
                            </a>
                          </Link>
                        </div>
                      </div>
                    </div>
                    <div>
                      <img
                        className='imgs'
                        key={img}
                        src={img}
                        alt='worktimg'
                      />
                    </div>
                  </div>
                );
              })}
              {/* car worksparts end*/}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default Work;

export async function getServerSideProps() {
  const res = await fetch('https://riponhaldar.github.io/json-api/db.json');
  const post = await res.json();

  return {
    props: {
      posts: post,
    },
  };
}
