import Head from 'next/head';
function about() {
  return (
    <>
      <Head>
        <title>ripon - about</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>
      <div className='text-gray-50'>about page</div>
    </>
  );
}

export default about;
