import Head from 'next/head';
import Image from 'next/image';
import ripon1st from '../../public/ripon1st.jpg';
function about() {
  return (
    <>
      <Head>
        <title>ripon - about</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>

      <div className='lg:container mx-auto lg:px-6 p-5  md:px-16 z-50'>
        <div className='mt-72 z-50'>
          <div className='sm:pl-10 pl-0 mb-20'>
            <div className='text-gray-900 font-domine sm:text-4xl text-lg font-bold '>
              <span className='overflow-hidden'>hello there,</span> <br />
              <span>My name is</span> <br />
              <span className='overflow-hidden underline text-red-400'>
                Ripon Haldar &
              </span>
              <br />
              <span> I am an Fronetend Developer</span>
            </div>
          </div>
          <div className='mt-10'>
            <div className=' w-full flex  relative overflow-hidden  transform -rotate-0	 z-0 '>
              <div className='scroll-text text-gray-900 text-8xl whitespace-nowrap font-domine uppercase'>
                <span>-Frontend</span> Developer <span>-Frontend</span>
                Developer <span>-Frontend</span> Developer
                <span>-Frontend</span> Developer <span>-Frontend</span>
                Developer
              </div>
            </div>
            <div className=' w-full flex  relative overflow-hidden  transform rotate-180	 z-0 '>
              <div className='scroll-text2 text-gray-900 text-8xl whitespace-nowrap font-domine uppercase'>
                <span>-Frontend</span> Developer <span>-Frontend</span>
                Developer <span>-Frontend</span> Developer
                <span>-Frontend</span> Developer <span>-Frontend</span>
                Developer
              </div>
            </div>
          </div>
          <div className='h-screen sm:mt-20 mt-10 sm:mb-8'>
            <div className='sm:float-right block lg:w-1/3  sm:mr-8'>
              <div className='text-3xl mb-2'>HI,</div>
              <div className='mb-4 text-lg leading-7'>
                Lorem ipsum dolor sit amet consectetur,adipisicing elit.
                Quibusdam, totam? Lorem ipsum dolor sit amet consectetur,
                adipisicing elit. Quibusdam, totam? Lorem ipsum dolor sit amet
                consectetur, adipisicing elit. Quibusdam, totam? Lorem ipsum
                dolor sit amet consectetur, adipisicing elit. Quibusdam, totam?
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Quibusdam, totam?
              </div>
              <div className='text-lg leading-7'>
                Lorem ipsum dolor sit amet consectetur,adipisicing elit.
                Quibusdam, totam? Lorem ipsum dolor sit amet consectetur,
                adipisicing elit. Quibusdam, totam? Lorem ipsum dolor sit amet
                consectetur, adipisicing elit.
              </div>
            </div>
          </div>
          <div className='sm:-mt-48 -mt-28'>
            <div className='sm:flex sm:justify-between sm:w-full '>
              <div className='text-gray-800 font-bold font-serif '>
                <span> PROGRAMMING LANGUAGES & OTHERS :</span>
              </div>
              <div className='flex text-gray-500 font-bold font-sans uppercase sm:leading-loose leading-7   mt-4 '>
                <ul className='mr-8'>
                  <li>
                    <span>-HTML/Css</span>
                  </li>
                  <li>
                    <span>-Sass</span>
                  </li>
                  <li>
                    <span>-Tailwindcss</span>
                  </li>
                  <li>
                    <span>-Bootstrap</span>
                  </li>
                </ul>
                <ul className='mr-8'>
                  <li>
                    <span>-React Js</span>
                  </li>
                  <li>
                    <span>-Next Js</span>
                  </li>
                  <li>
                    <span>-Node Js</span>
                  </li>
                  <li>
                    <span>-MongoDb</span>
                  </li>
                  <li>-React Js</li>
                </ul>
                <ul className='sm:mr-10'>
                  <li>
                    <span> -Gsap</span>
                  </li>
                </ul>
              </div>
            </div>
            <div className='xl:w-10/12	sm:flex sm:justify-between mt-4'>
              <div className='text-gray-800 font-bold font-serif '>
                <span> TOOLS:</span>
              </div>
              <div className='flex text-gray-500 font-bold font-sans uppercase sm:leading-loose leading-7 pl-10  flo mt-4 '>
                <ul className='mr-8'>
                  <li className=''>
                    <span>-Vs Code</span>
                  </li>
                  <li className=''>
                    <span>-Photoshop</span>
                  </li>
                  <li className=''>
                    <span>-Figma</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default about;
