import Head from 'next/head';
import About from '../components/homepage/About';
import Fastpage from '../components/homepage/Fastpage';
import Link from 'next/link';
import Image from 'next/image';
import { gsap, TimelineLite, Power3 } from 'gsap';
import { useEffect, useRef } from 'react';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
export default function Home({ posts }) {
  let projectText = useRef(null);

  let tl = new TimelineLite({ delay: 0.8 });
  useEffect(() => {
    const projectTextt = projectText.children[0];
    const projectTextSpan = projectText.children[1];

    tl.from(projectTextSpan, {
      duration: 5,
      opacity: 0,
      x: -50,
      scrollTrigger: {
        scrub: true,
        trigger: projectTextt,
        start: 'top bottom-=100',
        end: 'bottom bottom-=200',
        // markers: true,
      },
    });
    tl.from(projectTextt, {
      duration: 10,
      opacity: 0,
      x: 100,
      scrollTrigger: {
        scrub: true,
        trigger: projectTextt,
        start: 'top bottom-=100',
        end: 'bottom bottom-=200',
        // markers: true,
      },
    });
  });
  return (
    <>
      <Head>
        <title>ripon haldar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>
      <div className='cursor absolute w-2 h-2 bg-gray-200 rounded-full "transition duration-100 ease-in-out'></div>

      <div className='lg:container mx-auto lg:px-6 p-5  md:px-16 z-50'>
        <Fastpage />
        <About />
        {/* project parts*/}
        <div className=' mt-8'>
          <div className='relative'>
            <div className='text-3xl md:text-5xl relative  font-semibold  text-indigo-50 ml-2 capitalize mb-8'>
              <p
                className='inline-block px-2 relative'
                ref={(el) => (projectText = el)}
              >
                <span className='after__ele relative z-50'>Recent Project</span>
                <span className='absolute opacity-80 bg-purple-900	w-full h-3 md:h-4 left-0 bottom-1 md:bottom-0 z-0 '></span>
              </p>
            </div>
            <div className='text-gray-50  relative md:mx-12 mx-4 px-2'>
              <div>
                {/* car worksparts*/}

                {posts.map((post) => {
                  const { id, title, img, desc, url, view, category } = post;

                  return (
                    <div
                      key={id}
                      className='relative md:flex md:mt-40 items-center	e mt-10 justify-between'
                    >
                      <div className='xl:mr-20 mr-10 mb-10'>
                        <p className='text-red-100 text-2xl capitalize  font-serif mb-4'>
                          {title}
                        </p>
                        <span className='text-red-100 text-base'>{desc}</span>
                        <div className='text-gray-100 mt-4'>{category}</div>
                        <ul className='flex mt-4'>
                          <li className='mr-2'>
                            <Link href={view}>
                              <a className='bg-gray-50 py-1 px-2 font-bold text-red-800 rounded'>
                                Live
                              </a>
                            </Link>
                          </li>
                          <li>
                            <Link href={url}>
                              <a className='bg-gray-50 py-1 px-2 font-bold text-red-800 rounded'>
                                sources
                              </a>
                            </Link>
                          </li>
                        </ul>
                      </div>
                      <div>
                        <img key={img} src={img} alt='worktimg' />
                      </div>
                    </div>
                  );
                })}
                {/* car worksparts end*/}
              </div>
            </div>
          </div>
        </div>
        {/* project parts end*/}
      </div>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch('https://riponhaldar.github.io/json-api/db.json');
  const post = await res.json();

  return {
    props: {
      posts: post,
    },
  };
}
