import Head from 'next/head';
import About from '../components/homepage/About';
import Fastpage from '../components/homepage/Fastpage';
import Link from 'next/link';
import Image from 'next/image';
import { gsap, TimelineLite, Power3 } from 'gsap';
import { useEffect, useRef } from 'react';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
export default function Home({ posts }) {
  let projectText = useRef(null);

  let tl = new TimelineLite({ delay: 0.8 });
  useEffect(() => {
    const projectTextt = projectText.children[0];
    const projectTextSpan = projectText.children[1];

    tl.from(projectTextSpan, {
      duration: 5,
      opacity: 0,
      x: -50,
      scrollTrigger: {
        scrub: true,
        trigger: projectTextt,
        start: 'top bottom-=100',
        end: 'bottom bottom-=200',
        // markers: true,
      },
    });
    tl.from(projectTextt, {
      duration: 10,
      opacity: 0,
      x: 100,
      scrollTrigger: {
        scrub: true,
        trigger: projectTextt,
        start: 'top bottom-=100',
        end: 'bottom bottom-=200',
        // markers: true,
      },
    });
  });
  return (
    <>
      <Head>
        <title>ripon haldar</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/mack_herry.png' />
      </Head>
      <div className='cursor absolute w-2 h-2 bg-gray-200 rounded-full "transition duration-100 ease-in-out'></div>

      <div className='lg:container mx-auto lg:px-6 p-5  md:px-16 z-50'>
        <Fastpage />
        <div className=' relative'>
          <div className=' w-full flex relative  overflow-hidden  transform rotate-180 opacity-20	 z-0 '>
            <div className='scroll-text2 text-gray-900 text-8xl whitespace-nowrap font-domine uppercase'>
              <span>-Frontend</span> Developer <span>-Designer</span>
              Developer <span>-Frontend</span> Designer
              <span>-Frontend</span> Designer <span>-Frontend</span>
              Developer
            </div>
          </div>
          <div className=' w-full flex relative overflow-hidden opacity-50	 z-0 '>
            <div className='scroll-text text-gray-900 text-8xl whitespace-nowrap font-domine uppercase'>
              <span>-Frontend</span> Developer <span>-Designer</span>
              Developer <span>-Designer </span> Developer
              <span>-Frontend</span> Designer <span>-Frontend</span>
              Developer
            </div>
          </div>
        </div>
        <About />
        {/* project parts*/}
        <div className=' mt-8'>
          <div className='relative'>
            <div className='text-3xl md:text-5xl relative  font-semibold  text-gray-800 ml-2 capitalize mb-8'>
              <p
                className='inline-block px-2 relative'
                ref={(el) => (projectText = el)}
              >
                <span className='after__ele relative z-50'>Recent Project</span>
                <span className='absolute opacity-80 bg-purple-200	w-full h-3 md:h-4 left-0 bottom-1 md:bottom-0 z-0 '></span>
              </p>
            </div>
            <div className='text-gray-800  relative md:mx-12 mx-4 px-2'>
              <div>
                {/* car worksparts*/}
                <div className='mt-28'>
                  <div>
                    {posts.map((post) => {
                      const {
                        id,
                        title,
                        img,
                        desc,
                        url,
                        view,
                        category,
                        uses,
                      } = post;
                      return (
                        <div
                          key={id}
                          className='cards mb-20 relative max-w-full items-center border-2'
                        >
                          <Link href=''>
                            <a>
                              <img
                                className=' relative m-auto'
                                src={img}
                                alt=''
                              />
                              <div className='cards-text absolute  text-gray-800'>
                                <div className=' font-comorant font-semibold'>
                                  <span className='sm:text-lg text-sm font-comorant'>
                                    0{id}
                                  </span>
                                  <p className='whitespace uppercase drop-shadow text-6xl'>
                                    {title}
                                  </p>
                                  <div className='text-xl'>
                                    <em> #{uses.fremwork}</em>
                                    <em> #{uses.fremwork2}</em>
                                    <em> #{uses.fremwork3}</em>
                                  </div>
                                </div>
                              </div>
                            </a>
                          </Link>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* car worksparts end*/}
              </div>
            </div>
          </div>
        </div>
        {/* project parts end*/}
      </div>
    </>
  );
}
export async function getServerSideProps() {
  const res = await fetch('https://riponhaldar.github.io/json-api/db.json');
  const post = await res.json();

  return {
    props: {
      posts: post,
    },
  };
}
